- hosts: aws
  remote_user: jenkins
  tasks:
  - name: Pull sources from the repository.
    shell: ls
    ## git: 
    ##  repo: 'git@github.com:PaidUp/PUOrganization.git'
    ##  dest: /var/lib/jenkins/workspace/Dev_PUOrganization
    ##  version: develop