- hosts: aws
  remote_user: jenkins
  tasks:
  - name: Pull sources from the repository.
    git: 
      repo: git@github.com:PaidUp/PUOrganization.git
      dest: /var/lib/jenkins/workspace/Dev_PUOrganization
      version: develop

  - name: install node modules
    shell: npm install
    args:
      chdir: /var/lib/jenkins/workspace/Dev_PUOrganization

  - name: build to production
    shell: npm run prod
    args:
      chdir: /var/lib/jenkins/workspace/Dev_PUOrganization

  - name: NODE | Stop APP
    shell: pm2 stop organization-dev
    args:
      chdir: /var/lib/jenkins/workspace/Dev_PUOrganization
    ignore_errors: yes

  - name: NODE | Start APP
    shell: pm2 start dist/build.js --name organization-dev
    environment:
      NODE_ENV: development
    args:
      chdir: /var/lib/jenkins/workspace/Dev_PUOrganization
    register: myoutput

  - debug: 
      msg: "{{myoutput.stdout}}"
 