- hosts: dev
  vars:
    workspace: /var/lib/jenkins/workspace/Dev_PUOrganization
  tasks:
  - name: Pull sources from the repository.
    git: 
      repo: git@github.com:PaidUp/PUOrganization.git
      dest: '{{ workspace }}'
      version: develop
      force: yes

  - name: install node modules
    shell: npm install
    args:
      chdir: '{{ workspace }}'

  - name: NODE | Stop APP
    shell: pm2 stop organization-dev
    args:
      chdir: '{{ workspace }}'
    ignore_errors: yes

  - name: NODE | Start APP
    shell: npm run deploy-dev
    args:
      chdir: '{{ workspace }}'
 